// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opwcpqijoxytqzjvopyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wd2NwcWlqb3h5dHF6anZvcHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIzMDUsImV4cCI6MjA2NTQ4ODMwNX0.P8QfKKS_cVrWGbSwYyR9xzUB4R0WP_LP8CRetcaXB4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);